@startuml dd

class BestioleFactory {
  + liste_taux : map<string : double>
  + CreerBestiole():Bestiole
}

class Bestiole {
    + id : int
    + vitesse : double
    + position_x : double
    + position_y : double
    + orientation : double
    + taille : double
    + age : int
    + age_limite : int
    + estVivant : bool
    + resistance : double
    + detectabilité : double
    + mort(condition)
    + clonage()
    + Deplacer()
    + Percussion()
    + Detection()
}

class Millieu {
 + longueur : int
 + largeur : int

 +AjouterBestiole()
 +eliminerBestiole(Bestiole)
 +Maj()
}

class BestioleOreille {
    - delta : float
    - gamme : float
    + Detecter(Millieu) : Vector<Bool> 

}

Interface Accessoire {
  setParam() : void
}

Interface Capteur {
  Detecter(Millieu) : vector<Bool>
}


class BestioleNageoire {  
    - boost_max : float
    + setParam(vitesse v,boost_max) : void #setVit
}

class BestioleCamouflage {
  - phi_min : double
  - phi_max : double
  + setParam(phi_min,phi_max) : void #setDetect
}

class BestioleCarapace {
  - eta_max : double
  - omega_max : double
  + setParam(eta_max,omega_max) : void #setResist
}

class BestioleYeux {
  - alpha : Float
  - delta : Float
  - gamma : float
  + Detecter(Millieu) : Vector<Bool>
}

class IComportement {
  + Deplacer(Bestiole)
}

class Grégaire {
    -Deplacer(Bestiole) : void #ajustDirection

}

class Peureuse{
    -Deplacer(Bestiole) : void #def seuil+fuir

}

class Kamikaze{
    -Deplacer(Bestiole) : void #percuterKamikaze
}

class Prévoyant{
    -Deplacer(Bestiole) : void #ajuster trajectoire

}


class Multi{
    -adoptComportement(Bestiole) : void ?
}

BestioleFactory --> Bestiole : créer

Capteur *-- Bestiole
Capteur<|..BestioleOreille
Capteur<|..BestioleYeux

IComportement <|.. Grégaire
IComportement <|.. Peureuse
IComportement <|.. Kamikaze
IComportement <|.. Prévoyant
IComportement <|.. Multi
Bestiole *-- IComportement



Accessoire <|..BestioleNageoire
Accessoire <|..BestioleCarapace
Accessoire <|..BestioleCamouflage
Accessoire *-- Bestiole


Millieu --* "many" Bestiole : contient

Millieu -- BestioleFactory

@enduml
